file1 = open("demo.txt", "w")
file1.write("Hello, I am Anu Shalet Philip.")
file1 = open("demo.txt", "r")
content = file1.read()
print(content)
file1 = open("demo.txt", "a")
file1.write("I am from Kottayam.")
file1 = open("demo.txt", "r")
content = file1.read()
print(content)
file1.close()